version: '2'
services:
  stat-service:
    container_name: stat-service
    image: statservice/stat-service
    depends_on:
      - statdb
    ports:
      - 8099:8080
    environment:
      - DATABASE_HOST=statdb
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=statservice
      - DATABASE_PORT=5432
  statdb:
    container_name: stat_db
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=statservice
    ports:
      - 5434:5432